### ISSUE TITLE
请教下tbschedule的机制

### ISSUE THREAD

**Issue by alaxcc** [hungki/tbschedule-wed#3]
如果有多个节点，比如dev-A、dev-B，test-A，test-B，分别连接了开发环境的数据库和测试环境的数据库。

这时候调度结果会怎样？

会从dev-A节点取出开发环境的数据，然后分配个test-B节点处理从而进入测试环境的数据库吗？

**Comment by wednesday-osc** [comment]
如果配置的是同一套zookeeper地址则会全部调用。两个解决版本：1、不嫌麻烦的话配置4道任务，分别指定IP运行。2、配置2道任务，启用隔离space。详见：https://my.oschina.net/wednesday/blog/1591716

**Comment by alaxcc** [comment]
好的，感谢！

发自我的 iPhone
