### ISSUE TITLE
请教个关于tbs的坑

### ISSUE THREAD

**Issue by alaxcc** [hungki/tbschedule-wed#4]
请教个问题，tbs连接zk出现错误提示。
<br/>
但点击保存后，zk上会马上出现连接的节点，是不是说明连接成功了？
<br/>
这个看tbs所在tomcat的logs也没有想过错误日志，zk各节点间通过2181端口连接也是可以正常连接操作的，请教怎么解决？

![avatar](https://wx3.sinaimg.cn/mw690/7f366bb3ly1fvmy1z1uf2j20us08k3zk.jpg)

![avatar](https://wx1.sinaimg.cn/mw690/7f366bb3ly1fvmy26ng0pj20cb01emx6.jpg)

**Comment by wednesday-osc** [comment]
建议zk尽量5个节点，另外目前版本遇到这种情况只能重启应用。请期待后续优化
