### ISSUE TITLE
目前版本使用Timer进行调度，高频任务长期执行会积累deley，使用SLEEP模式当deley达到内置500ms时该task假死

### ISSUE THREAD

**Issue by wednesday-osc** [hungki/tbschedule-wed#7]

**Comment by wednesday-osc** [comment]
预计1.0.1版本修复。
1.使用ScheduledExcutorService替代Timer
2.使用org.apache.curator.framework.CuratorFrameworkFactory替代org.apache.zookeeper.ZooKeeper并重构API为新Console做准备

**Comment by peidw** [comment]
1.0.1版本何时发布呢

**Comment by wednesday-osc** [comment]
> 1.0.1版本何时发布呢

年前行里太忙了，预计3月发布，感谢关注！

**Comment by wednesday-osc** [comment]
1.0.1-GA已发布，功能测试passed暂未经生产压测，建议暂时不要在生产环境中使用。
